### ISSUE TITLE
Mod is not starting

### ISSUE THREAD

**Issue by LockBlock-dev** [arukuka/wotmods-discord-rich-presence#9]
The mod is not starting because of an error with a dependency.

python.log:
```
2021-11-11 15:15:21.717: INFO: [PY_DEBUG] Checking D:/Programmes/World_of_Tanks_EU/res_mods/1.14.1.3/: mods not found
2021-11-11 15:15:21.717: INFO: [PY_DEBUG] Checking D:/Programmes/World_of_Tanks_EU/mods/1.14.1.3/: mods found
2021-11-11 15:15:21.717: INFO: [PY_DEBUG] Mod package 'd:/programmes/world_of_tanks_eu/mods/1.14.1.3/arukuka.discord_rich_presence_0.1.3.wotmod' loaded
2021-11-11 15:15:21.717: INFO: [PY_DEBUG] Mod package 'd:/programmes/world_of_tanks_eu/mods/1.14.1.3/com.modxvm.xfw.loader_8.8.1.0006.wotmod' loaded
2021-11-11 15:15:21.717: INFO: [PY_DEBUG] Mod package 'd:/programmes/world_of_tanks_eu/mods/1.14.1.3/com.modxvm.xfw.native_2.1.9.wotmod' loaded

...

2021-11-11 15:12:35.691: INFO: [root] [XFW/Entrypoint]
2021-11-11 15:12:35.691: INFO: [root] [XFW/Entrypoint] WoT Working Directory: D:\Programmes\World_of_Tanks_EU
2021-11-11 15:12:35.691: INFO: [root] [XFW/Entrypoint] Path to root: ./
2021-11-11 15:12:35.730: INFO: [root] [XFW/Loader] Loading mod: com.modxvm.xfw.native, v. 2.1.9
2021-11-11 15:12:43.422: ERROR: [[XFW/Native]] [load_native] Error on loading native module 'python27.dll' from package 'com.modxvm.xfw.native'
Traceback (most recent call last):
  File "./src/wot_python/__init__.py", line 77, in load_native
SystemError: dynamic module not initialized properly

2021-11-11 15:12:43.422: ERROR: [[XFW/Native]] [xfw_module_init] Failed to load python27
2021-11-11 15:12:43.422: ERROR: [root] [XFW/Loader] Loading mod: 'com.modxvm.xfw.native' FAILED (flag)
2021-11-11 15:12:43.422: WARNING: [root] [XFW/Loader] Error with mod: 'arukuka.discord_rich_presence'. Feature failed: 'native' in package 'com.modxvm.xfw.native'
2021-11-11 15:12:43.422: ERROR: Traceback (most recent call last):
2021-11-11 15:12:43.422: ERROR:   File "D:/a/wotmods-discord-rich-presence/wotmods-discord-rich-presence/package/res/scripts/client/gui/mods/mod_discord_rich_presence.py", line 276, in init
2021-11-11 15:12:43.422: ERROR:   File "D:/a/wotmods-discord-rich-presence/wotmods-discord-rich-presence/package/res/scripts/client/gui/mods/mod_discord_rich_presence.py", line 79, in __init__
2021-11-11 15:12:43.422: ERROR: AttributeError: 'NoneType' object has no attribute 'unpack_native'
```

**Comment by arukuka** [comment]
I do apologize for inconvenience.
I think that it needs to upgrade the version of [XFM/Native](https://gitlab.com/xvm/xfw/xfw.native) on which my mod depends.

I should rewrite the following line to upgrade it, but I cannot make time to confirm that my mod works until at least the end of the year.
https://github.com/arukuka/wotmods-discord-rich-presence/blob/82aea5f83765f3d23c2306a9c9ebce826152be88/project.ini#L6

It might be helpful to know how to use build scripts by the following.
https://github.com/arukuka/wotmods-discord-rich-presence/blob/82aea5f83765f3d23c2306a9c9ebce826152be88/.github/workflows/build.yml#L22-L28

So sorry.

Sincerely,

**Comment by LockBlock-dev** [comment]
Thanks for your answer,

Take your time, there is no urge.
